name: Ping
author: Sketch
version: 1.0.0.0
platform: Any
description: Check target availability
src: modules/src/ping.py

inputs:
  tgt_ip: null
  count: 1
  interval: 1
  timeout: 2

outputs:
  - tgt_ip
  - sent
  - received
  - avg_latency